services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped

  postgres:
    image: postgres:latest
    ports:
      - '5434:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    logging:
      driver: none

volumes:
  data:
